sudo: required
addons:
  chrome: stable

language: node_js
node_js:
- "node"

branches:
  only:
    - master

before_script:
  - cd frontend
  - npm install -g @angular/cli
  - npm install

script:
  - cd frontend
  - ng build --prod --aot
  - ng test