sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "9.8"

branches:
  only:
    - master

before_script:
  - cd frontend
  - npm install -g @angular/cli

script:
  - cd frontend
  - ng build --prod --aot
  - ng test