sudo: required
addons:
  chrome: stable
  postgresql: "9.4"
env:
  - SPRING_ACTIVE_PROFILES=postgresql
matrix:
  include:
    - language: java
      services:
        - postgresql
      before_script:
        - pwd
        - createdb H2MSDatabase

    - language: node_js
      node_js:
      - "node"
      before_script:
        - pwd
        - cd frontend
        - npm install

      script:
        - ng build --prod --aot
        - ng test
notifications:
    slack: 2018swecapstone:IPDjX0h4Za0ztVoCHZXAoq0q