sudo: required
addons:
  chrome: stable

matrix:
  include:
    - language: node_js
      node_js:
      - "node"

      before_script:
        - cd frontend
        - npm install

      script:
        - ng build --prod --aot
        - ng test