version: '3.1'
services:
  pallmallweb:
    image: cscie599/pallmall
    ports:
      - "8080:8080"
    #volumes:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  adminer:
    image: adminer
    ports:
      - "8081:8080"